import type { APIRoute } from 'astro';
import JSZip from 'jszip';
import { getAdminClient } from '../../lib/supabase';

interface ComponentRequest {
  path: string;
  type: string;
  name: string;
}

/**
 * POST /api/download-collection
 * Body: { collectionName: string, components: ComponentRequest[] }
 * Returns a ZIP file with the correct .claude/ folder structure.
 */
export const POST: APIRoute = async ({ request }) => {
  const body = await request.json();
  const components: ComponentRequest[] = body.components ?? [];
  const collectionName: string = body.collectionName ?? 'my-collection';

  if (!components.length) {
    return new Response(JSON.stringify({ error: 'No components provided' }), { status: 400 });
  }

  const supabase = getAdminClient();

  // Fetch all component content in one query
  const paths = components.map((c) => c.path);
  const pathsWithExt = paths.flatMap((p) => [p, `${p}.md`, `${p}.json`]);

  const { data: rows } = await supabase
    .from('components')
    .select('path, type, name, content')
    .in('path', pathsWithExt);

  // Build a lookup by path (normalised — strip extension)
  const contentMap: Record<string, { content: string; type: string; name: string }> = {};
  for (const row of rows ?? []) {
    const key = row.path.replace(/\.(md|json)$/, '');
    contentMap[key] = { content: row.content ?? '', type: row.type, name: row.name };
  }

  // Increment downloads for all fetched components (fire and forget)
  supabase
    .from('components')
    .select('path, downloads')
    .in('path', pathsWithExt)
    .then(({ data }) => {
      if (!data) return;
      for (const row of data) {
        supabase
          .from('components')
          .update({ downloads: (row.downloads ?? 0) + 1 })
          .eq('path', row.path)
          .then(() => {});
      }
    });

  const zip = new JSZip();

  const settingsChunks: Record<string, unknown>[] = [];
  const mcpChunks: Record<string, unknown>[] = [];

  for (const comp of components) {
    const key = comp.path.replace(/\.(md|json)$/, '');
    const row = contentMap[key];
    const content = row?.content ?? `# ${comp.name}\n\nContent not found.`;
    const type = comp.type.replace(/s$/, ''); // normalise plural → singular
    const fname = comp.name.replace(/\.(md|json)$/, '');

    if (type === 'agent' || type === 'agents') {
      zip.file(`.claude/agents/${fname}.md`, content);
    } else if (type === 'command' || type === 'commands') {
      zip.file(`.claude/commands/${fname}.md`, content);
    } else if (type === 'skill' || type === 'skills') {
      // Skills live in their own subfolder: .claude/skills/<name>/SKILL.md
      zip.file(`.claude/skills/${fname}/SKILL.md`, content);
    } else if (type === 'hook' || type === 'hooks') {
      // Individual hook scripts
      zip.file(`.claude/hooks/${fname}.sh`, content);
    } else if (type === 'setting' || type === 'settings') {
      // Merge into settings.json
      try { settingsChunks.push(JSON.parse(content)); } catch { /* skip malformed */ }
    } else if (type === 'mcp' || type === 'mcps') {
      // Merge into .mcp.json
      try { mcpChunks.push(JSON.parse(content)); } catch { /* skip malformed */ }
    } else {
      // Fallback: put in .claude/ root
      zip.file(`.claude/${fname}.md`, content);
    }
  }

  // Merge settings
  if (settingsChunks.length) {
    const merged = settingsChunks.reduce((acc, chunk) => ({ ...acc, ...chunk }), {});
    zip.file('.claude/settings.json', JSON.stringify(merged, null, 2));
  }

  // Merge MCPs into .mcp.json
  if (mcpChunks.length) {
    const merged = { mcpServers: {} as Record<string, unknown> };
    for (const chunk of mcpChunks) {
      const servers = (chunk as any).mcpServers ?? chunk;
      Object.assign(merged.mcpServers, servers);
    }
    zip.file('.mcp.json', JSON.stringify(merged, null, 2));
  }

  // Add a README
  const readmeLines = [
    `# ${collectionName}`,
    '',
    'Generated by [Consulting 2.0 Agentic Marketplace](https://marketplace.consulting20.com)',
    '',
    '## Installation',
    '',
    'Copy the `.claude/` folder into your project root (or `~/.claude/` for global install).',
    '',
    '## Components',
    '',
    ...components.map((c) => `- **${c.name}** (${c.type})`),
  ];
  zip.file('README.md', readmeLines.join('\n'));

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
  const safeName = collectionName.toLowerCase().replace(/[^a-z0-9]+/g, '-');

  return new Response(zipBuffer, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${safeName}.zip"`,
    },
  });
};
