import type { APIRoute } from 'astro';
import * as JSZipModule from 'jszip';
import { getAdminClient } from '../../lib/supabase';

const JSZip = (JSZipModule as any).default ?? JSZipModule;

interface ComponentRequest {
  path: string;
  type: string;
  name: string;
}

function toSingular(type: string): string {
  const map: Record<string, string> = {
    agents: 'agent', skills: 'skill', commands: 'command',
    hooks: 'hook', mcps: 'mcp', settings: 'setting', templates: 'template',
  };
  return map[type] ?? type;
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const body = await request.json();
    const components: ComponentRequest[] = body.components ?? [];
    const collectionName: string = body.collectionName ?? 'my-collection';

    if (!components.length) {
      return new Response(JSON.stringify({ error: 'No components provided' }), { status: 400 });
    }

    const supabase = getAdminClient();
    const allPaths = components.flatMap((c) => {
      const p = c.path.replace(/\.(md|json)$/, '');
      return [p, `${p}.md`, `${p}.json`];
    });

    const { data: rows } = await supabase
      .from('components')
      .select('path, type, name, content, downloads')
      .in('path', allPaths);

    const contentMap: Record<string, string> = {};
    for (const row of rows ?? []) {
      const key = row.path.replace(/\.(md|json)$/, '');
      if (row.content) contentMap[key] = row.content;
    }

    const zip = new JSZip();
    const settingsChunks: Record<string, unknown>[] = [];
    const mcpChunks: Record<string, unknown>[] = [];
    const installLines: string[] = [];

    // NOTE: We use visible folder names (no leading dot) so files are visible
    // on all OS. The install.sh script moves them to the correct .claude/ location.

    for (const comp of components) {
      const key = comp.path.replace(/\.(md|json)$/, '');
      const content = contentMap[key] ?? `# ${comp.name}\n\nSource: https://marketplace.consulting20.com`;
      const fname = comp.name.replace(/\.(md|json)$/, '').trim();
      const type = toSingular(comp.type);

      if (type === 'setting') {
        try { settingsChunks.push(JSON.parse(content)); } catch { /* skip */ }
        continue;
      }
      if (type === 'mcp') {
        try { mcpChunks.push(JSON.parse(content)); } catch { /* skip */ }
        continue;
      }
      if (type === 'agent') {
        zip.file(`agents/${fname}.md`, content);
        installLines.push(`cp agents/${fname}.md .claude/agents/${fname}.md`);
      } else if (type === 'command') {
        zip.file(`commands/${fname}.md`, content);
        installLines.push(`cp commands/${fname}.md .claude/commands/${fname}.md`);
      } else if (type === 'skill') {
        zip.file(`skills/${fname}/SKILL.md`, content);
        installLines.push(`cp -r skills/${fname} .claude/skills/${fname}`);
      } else if (type === 'hook') {
        zip.file(`hooks/${fname}.sh`, content);
        installLines.push(`cp hooks/${fname}.sh .claude/hooks/${fname}.sh`);
      } else {
        zip.file(`${fname}.md`, content);
        installLines.push(`cp ${fname}.md .claude/${fname}.md`);
      }
    }

    if (settingsChunks.length) {
      const merged = settingsChunks.reduce((acc, c) => ({ ...acc, ...c }), {});
      zip.file('settings.json', JSON.stringify(merged, null, 2));
      installLines.push('# Merge settings.json into .claude/settings.json manually');
    }

    if (mcpChunks.length) {
      const merged = { mcpServers: {} as Record<string, unknown> };
      for (const c of mcpChunks) Object.assign(merged.mcpServers, (c as any).mcpServers ?? c);
      zip.file('mcp.json', JSON.stringify(merged, null, 2));
      installLines.push('# Merge mcp.json into .mcp.json manually');
    }

    // install.sh — creates .claude/ dirs and copies everything
    const installSh = [
      '#!/bin/bash',
      '# Generated by Consulting 2.0 Agentic Marketplace',
      '# Run this script from the folder where you unzipped the collection',
      '# Usage: bash install.sh [--global]',
      '',
      'TARGET=".claude"',
      'if [ "$1" = "--global" ]; then',
      '  TARGET="$HOME/.claude"',
      '  echo "Installing globally to $TARGET"',
      'else',
      '  echo "Installing to current project: $TARGET"',
      'fi',
      '',
      'mkdir -p "$TARGET/agents" "$TARGET/skills" "$TARGET/commands" "$TARGET/hooks"',
      '',
      '[ -d agents ]   && cp -r agents/.   "$TARGET/agents/"',
      '[ -d skills ]   && cp -r skills/.   "$TARGET/skills/"',
      '[ -d commands ] && cp -r commands/. "$TARGET/commands/"',
      '[ -d hooks ]    && cp -r hooks/.    "$TARGET/hooks/"',
      '',
      'echo "Done! Components installed to $TARGET"',
      'echo "Restart Claude Code to pick up new agents and skills."',
    ].join('\n');

    zip.file('install.sh', installSh);

    zip.file('README.md', [
      `# ${collectionName}`,
      '',
      'Generated by [Consulting 2.0 Agentic Marketplace](https://marketplace.consulting20.com)',
      '',
      '## Install',
      '',
      '**Option 1 — Run the install script:**',
      '```bash',
      'bash install.sh          # install to current project .claude/',
      'bash install.sh --global # install globally to ~/.claude/',
      '```',
      '',
      '**Option 2 — Manual copy:**',
      'Copy `agents/`, `skills/`, `commands/`, `hooks/` into your project\'s `.claude/` folder.',
      '',
      '> **macOS users:** if you unzip and only see README.md and install.sh,',
      '> the other folders are there — press **Cmd + Shift + .** in Finder to show hidden files.',
      '> Or just run `bash install.sh` from Terminal.',
      '',
      '## Components',
      ...components.map((c) => `- **${c.name}** (${c.type})`),
    ].join('\n'));

    const zipBuffer = await zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE' });
    const safeName = collectionName.toLowerCase().replace(/[^a-z0-9]+/g, '-');

    return new Response(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${safeName}.zip"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch (err: any) {
    console.error('download-collection error:', err);
    return new Response(JSON.stringify({ error: err?.message ?? 'Unknown error' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
};
