import type { APIRoute } from 'astro';
import * as JSZipModule from 'jszip';
import { getAdminClient } from '../../lib/supabase';

// Handle both CJS and ESM exports of jszip
const JSZip = (JSZipModule as any).default ?? JSZipModule;

interface ComponentRequest {
  path: string;
  type: string;
  name: string;
}

function toSingular(type: string): string {
  const map: Record<string, string> = {
    agents: 'agent', skills: 'skill', commands: 'command',
    hooks: 'hook', mcps: 'mcp', settings: 'setting', templates: 'template',
  };
  return map[type] ?? type;
}

function destPath(type: string, fname: string): string {
  const t = toSingular(type);
  if (t === 'agent')   return `.claude/agents/${fname}.md`;
  if (t === 'command') return `.claude/commands/${fname}.md`;
  if (t === 'skill')   return `.claude/skills/${fname}/SKILL.md`;
  if (t === 'hook')    return `.claude/hooks/${fname}.sh`;
  if (t === 'setting') return null as any; // merged into settings.json
  if (t === 'mcp')     return null as any; // merged into .mcp.json
  return `.claude/${fname}.md`;
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const body = await request.json();
    const components: ComponentRequest[] = body.components ?? [];
    const collectionName: string = body.collectionName ?? 'my-collection';

    if (!components.length) {
      return new Response(JSON.stringify({ error: 'No components provided' }), { status: 400 });
    }

    // Fetch content from Supabase
    const supabase = getAdminClient();
    const allPaths = components.flatMap((c) => {
      const p = c.path.replace(/\.(md|json)$/, '');
      return [p, `${p}.md`, `${p}.json`];
    });

    const { data: rows } = await supabase
      .from('components')
      .select('path, type, name, content')
      .in('path', allPaths);

    const contentMap: Record<string, string> = {};
    for (const row of rows ?? []) {
      const key = row.path.replace(/\.(md|json)$/, '');
      if (row.content) contentMap[key] = row.content;
    }

    // Increment downloads async
    if (rows?.length) {
      supabase
        .from('components')
        .upsert(
          rows.map((r) => ({ ...r, downloads: (r.downloads ?? 0) + 1 })),
          { onConflict: 'path' }
        )
        .then(() => {});
    }

    const zip = new JSZip();
    const settingsChunks: Record<string, unknown>[] = [];
    const mcpChunks: Record<string, unknown>[] = [];

    for (const comp of components) {
      const key = comp.path.replace(/\.(md|json)$/, '');
      const content = contentMap[key] ?? `# ${comp.name}\n\nInstall from: https://marketplace.consulting20.com`;
      const fname = comp.name.replace(/\.(md|json)$/, '').trim();
      const type = toSingular(comp.type);

      if (type === 'setting') {
        try { settingsChunks.push(JSON.parse(content)); } catch { /* skip */ }
        continue;
      }
      if (type === 'mcp') {
        try { mcpChunks.push(JSON.parse(content)); } catch { /* skip */ }
        continue;
      }

      const path = destPath(type, fname);
      if (path) zip.file(path, content);
    }

    if (settingsChunks.length) {
      const merged = settingsChunks.reduce((acc, c) => ({ ...acc, ...c }), {});
      zip.file('.claude/settings.json', JSON.stringify(merged, null, 2));
    }

    if (mcpChunks.length) {
      const merged = { mcpServers: {} as Record<string, unknown> };
      for (const c of mcpChunks) {
        Object.assign(merged.mcpServers, (c as any).mcpServers ?? c);
      }
      zip.file('.mcp.json', JSON.stringify(merged, null, 2));
    }

    zip.file('README.md', [
      `# ${collectionName}`,
      '',
      'Generated by [Consulting 2.0 Agentic Marketplace](https://marketplace.consulting20.com)',
      '',
      '## Install',
      'Copy the `.claude/` folder into your project root, or `~/.claude/` for global use.',
      '',
      '## Components',
      ...components.map((c) => `- **${c.name}** (${c.type})`),
    ].join('\n'));

    const zipBuffer = await zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE' });
    const safeName = collectionName.toLowerCase().replace(/[^a-z0-9]+/g, '-');

    return new Response(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${safeName}.zip"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch (err: any) {
    console.error('download-collection error:', err);
    return new Response(JSON.stringify({ error: err?.message ?? 'Unknown error' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
};
